apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: datadog-agent
build:
  platforms: [ "linux/arm64" ]
  tagPolicy:
    gitCommit: {
        variant: "AbbrevCommitSha"
    }
  local:
    push: false
    concurrency: 0
  artifacts:
    # TODO Add a hook to do 'git config --global --add safe.directory /home/datadog/go/src/github.com/DataDog/datadog-agent'
    - image: agent
      custom:
        buildCommand: "DELVE=1 docker exec datadog-agent-devenv bash -c \"
          inv -e agent.build && \
          inv agent.hacky-dev-image-build --base-image=gcr.io/datadoghq/agent:7-rc --target-image=$IMAGE\""
    - image: clusteragent
      custom:
        buildCommand: "DELVE=1 docker exec datadog-agent-devenv bash -c \"
          inv -e cluster-agent.build && \
          inv cluster-agent.hacky-dev-image-build --target-image=$IMAGE\""
deploy:
  helm:
    releases:
      - name: datadog-agent
        remoteChart: datadog/datadog
        version: 3.82.0
        skipTests: true
        setValueTemplates:
          datadog:
            apiKey: "{{cmd \"bash\" \"-c\" \"echo $DD_API_KEY\"}}"
            appKey: "{{cmd \"bash\" \"-c\" \"echo $DD_APP_KEY\"}}"
          agents.image:
            repository: "{{.IMAGE_REPO_agent}}"
            tag: "{{.IMAGE_TAG_agent}}@{{.IMAGE_DIGEST_agent}}"
            doNotCheckTag: true
          clusterAgent:
            replicas: 2
            createPodDisruptionBudget: true
            image:
              repository: "{{.IMAGE_REPO_clusteragent}}"
              tag: "{{.IMAGE_TAG_clusteragent}}"
              doNotCheckTag: true
          clusterCheckRunner.image:
            repository: "{{.IMAGE_REPO_agent}}"
            tag: "{{.IMAGE_TAG_agent}}"
            doNotCheckTag: true
